window.SIP_OF_GHOULAID_CATALOG = [
    { id: '121119213', name: 'Melting Alien Holder', category: 'Accessories', icon: '👽', price: 30, stock: 1, description: 'A creepy-cute 3D-printed alien holder for wax melts, brushes, pens, or plants.', image: 'https://assets.bigcartel.com/product_images/431094864/14389004-817f-4f0a-92c5-4ebd9fe3722c.png', sourceUrl: 'https://www.sipofghoulaid.com/product/melting-alien-holder', available: true },
    { id: '121113183', name: 'Custom Wax Melt Order', category: 'Wax Melts', icon: '🎃', price: 100, stock: 5, description: 'A made-from-scratch custom wax melt design with your idea and a spooky little laboratory touch.', image: 'https://assets.bigcartel.com/product_images/431072568/IMG_2623.jpeg', sourceUrl: 'https://www.sipofghoulaid.com/product/custom-wax-melt-order', available: true, variants: [{ id: '121113183-sweet', name: 'Sweet scent', price: 100, stock: 2, options: { 'Scent family': 'Sweet' } }, { id: '121113183-fresh', name: 'Fresh scent', price: 100, stock: 2, options: { 'Scent family': 'Fresh' } }, { id: '121113183-spooky', name: 'Spooky scent', price: 105, stock: 1, options: { 'Scent family': 'Spooky' } }] },
    { id: '121111551', name: 'Custom Mini Melt Order', category: 'Wax Melts', icon: '👻', price: 45, stock: 3, description: 'Tiny custom wax melts with the same big spooky process, made from your idea.', image: 'https://assets.bigcartel.com/product_images/431066826/IMG_2542.jpeg', sourceUrl: 'https://www.sipofghoulaid.com/product/custom-mini-melt-order', available: true, variants: [{ id: '121111551-pastel', name: 'Pastel finish', price: 45, stock: 2, options: { Finish: 'Pastel' } }, { id: '121111551-uv', name: 'UV finish', price: 48, stock: 1, options: { Finish: 'UV reactive' } }] },
    { id: '121111353', name: 'UV Alien Head Wax Melts', category: 'Wax Melts', icon: '👽', price: 20, stock: 1, description: 'Handmade alien-head melts that glow under UV light and bring a little invasion to your warmer.', image: 'https://assets.bigcartel.com/product_images/431066280/IMG_2540.jpeg', sourceUrl: 'https://www.sipofghoulaid.com/product/uv-alien-head-wax-melts', available: true },
    { id: '121109868', name: 'UV Reactive UFO Melts', category: 'Wax Melts', icon: '🛸', price: 18, stock: 1, description: 'A set of tiny saucer melts made for neon color, jelly wax, and blacklight weirdness.', image: 'https://assets.bigcartel.com/product_images/431061981/IMG_2450.jpeg', sourceUrl: 'https://www.sipofghoulaid.com/product/uv-reactive-ufo-melts', available: true },
    { id: '121059912', name: 'Flame On Bookmark', category: 'Accessories', icon: '🔥', price: 10, stock: 1, description: 'A fiery little bookmark for readers who like their current chapter extra hot.', image: 'https://assets.bigcartel.com/product_images/430880616/IMG_2278.jpeg', sourceUrl: 'https://www.sipofghoulaid.com/product/flame-on-bookmark', available: true },
    { id: '121008330', name: 'Gallows Coaster and Tea Bag Holder', category: 'Accessories', icon: '☕', price: 30, stock: 1, description: 'A 3D-printed gallows tea bag holder that keeps your mug ritual delightfully grim.', image: 'https://assets.bigcartel.com/product_images/430693542/IMG_2018.jpeg', sourceUrl: 'https://www.sipofghoulaid.com/product/gallows-coaster-and-tea-bag-holder', available: true },
    { id: '121008153', name: 'Custom Headset Holder', category: 'Accessories', icon: '🎧', price: 100, stock: 1, description: 'A custom headset holder summoned from your reference picture and favorite strange details.', image: 'https://assets.bigcartel.com/product_images/430689648/IMG_1999.jpeg', sourceUrl: 'https://www.sipofghoulaid.com/product/Custom-headset-holder', available: true },
    { id: '121007163', name: 'Jason Headset Holder', category: 'Accessories', icon: '🎧', price: 55, stock: 1, description: 'A horror-themed headset holder that brings a slasher-movie vibe to your desk.', image: 'https://assets.bigcartel.com/product_images/430686315/IMG_1926.jpeg', sourceUrl: 'https://www.sipofghoulaid.com/product/Jason-headset-holder', available: true },
    { id: '121002057', name: 'Frankenstein Headset Holder', category: 'Accessories', icon: '🎧', price: 55, stock: 1, description: 'A detailed Frankenstein-inspired headset holder for a monster-worthy setup.', image: 'https://assets.bigcartel.com/product_images/430670724/IMG_1905.jpeg', sourceUrl: 'https://www.sipofghoulaid.com/product/frankenstein-headset-holder', available: true },
    { id: '119666553', name: 'UFO Record Topper', category: 'Accessories', icon: '🛸', price: 15, stock: 1, description: 'An extraterrestrial record topper to give your vinyl player a cosmic upgrade.', image: 'https://assets.bigcartel.com/product_images/431068725/IMG_2563.jpeg', sourceUrl: 'https://www.sipofghoulaid.com/product/record-Topper', available: true },
    { id: '119665884', name: 'Smut Bookmark Bundle', category: 'Accessories', icon: '📚', price: 10, stock: 1, description: 'A cheeky two-bookmark bundle for the readers with the hottest shelves.', image: 'https://assets.bigcartel.com/product_images/430689102/IMG_1936.jpeg', sourceUrl: 'https://www.sipofghoulaid.com/product/smut-bookmark-bundle', available: true },
    { id: '119394915', name: 'Godzilla Headset Holder', category: 'Accessories', icon: '🦖', price: 55, stock: 1, description: 'A detailed monster headset holder with scales, teeth, and big desk energy.', image: 'https://assets.bigcartel.com/product_images/430670256/IMG_1885.jpeg', sourceUrl: 'https://www.sipofghoulaid.com/product/godzilla-headset-holder', available: true },
    { id: '119292498', name: 'Zombie Holder', category: 'Accessories', icon: '🧟', price: 30, stock: 1, description: 'A creepy-cute 3D-printed zombie holder for your wax melts and desk treasures.', image: 'https://assets.bigcartel.com/product_images/431095770/87e30251-4b8f-4850-8190-95bc9ca13ede.png', sourceUrl: 'https://www.sipofghoulaid.com/product/zombie-holder', available: true },
    { id: '118842948', name: 'Summon a Boo Wax Melts', category: 'Wax Melts', icon: '🔮', price: 20, stock: 1, description: 'Soy wax ghosts and planchettes with UV-reactive details for your warmer.', image: 'https://assets.bigcartel.com/product_images/431067504/IMG_2554.jpeg', sourceUrl: 'https://www.sipofghoulaid.com/product/boo-sheet-wax-melt-set', available: true },
    { id: '118842819', name: '"But Daddy I Love Him!" Ghostface Soy Wax Melt', category: 'Wax Melts', icon: '🔪', price: 15, stock: 1, description: 'A Ghostface-inspired soy wax melt for fans of scary movies and spooky scent throws.', image: 'https://assets.bigcartel.com/product_images/431081190/IMG_2616.jpeg', sourceUrl: 'https://www.sipofghoulaid.com/product/pink-ghostface-soy-wax-melts', available: true }
];
